### ISSUE TITLE
Design the home page

### ISSUE THREAD

**Issue by clarissa-chan** [UoaWDCC/aspa-portal-v2#2]
Utilise Figma to create a rough design of the home page.

**Comment by ykim583** [comment]
Created two prototype design for the home page of ASPA, both for desktop size 1920x1080 size.
One - concept of bright pool game
Second - concept of elegant pool game.

**Comment by ykim583** [comment]
Edited the navigation bar.
Payment -> Upcoming Events
Included footer bar for Design type 1.
